In [198]:
import pandas as pd
import re

# Data Import

In [2]:
programs = pd.read_csv('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/original_data/programs.csv')
youtube = pd.read_csv('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/original_data/youtube.csv')
fb4 = pd.read_csv('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/original_data/1_2020-6_15_2020.csv')
fb5 = pd.read_csv('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/original_data/6_15_2020-present.csv')
fb1 = pd.read_csv('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/original_data/1_2019-6_15_2019.csv')
fb2 = pd.read_csv('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/original_data/6_15_2019-11_2019.csv')
fb3 = pd.read_csv('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/original_data/12_2019.csv')
website = pd.read_csv('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/original_data/Monthly Report_Traffic Sources_Table.csv')

# Data Cleaning

## Programs

In [3]:
programs.iloc[276]
programs = programs.drop(range(277,310))

In [4]:
programs.tail()

         Date  ... Unnamed: 21
272  08/20/20  ...         NaN
273  08/27/20  ...         NaN
274  09/01/20  ...         NaN
275  09/24/20  ...         NaN
276  10/12/20  ...         NaN

[5 rows x 22 columns]

In [5]:
columns = programs.columns
columns

Index(['Date', 'Program Title', 'Live Stream', 'YouTube Views', 'FB Views',
       'Attendance (in seats)', 'Hours', 'Program Series', 'Venue',
       'Type of Program', 'Male Speakers', 'Female Speakers',
       'People of Color (informal)', '# of Speakers', 'Partner/ event',
       'Total Viewing', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21'],
      dtype='object')

In [6]:
programs.drop(columns[-7:], axis=1, inplace=True)
programs.drop(['YouTube Views', 'FB Views', '# of Speakers'], axis=1, inplace=True)
programs

         Date  ...                 Partner/ event
0     10/5/07  ...                            NaN
1    10/29/07  ...                            NaN
2     2/22/08  ...                            NaN
3     3/12/08  ...                            NaN
4    5/5&7/08  ...                            NaN
..        ...  ...                            ...
272  08/20/20  ...          IGB; Kleinmutz Center
273  08/27/20  ...                    Chitown Bio
274  09/01/20  ...                            NaN
275  09/24/20  ...         IGB; Kleinmuntz Center
276  10/12/20  ...  University of Illinois System

[277 rows x 12 columns]

In [7]:
programs.fillna('0', inplace=True)
programs['Partner/ event'].replace(0, 'none', inplace=True)

In [8]:
# partners_tbl = pd.Series(new_partners_nolist)
# partners_tbl = pd.DataFrame(pd.Series(partners_tbl.unique()))
# partners_tbl.reset_index(inplace=True)
# partners_tbl.rename(columns={'index': 'partner_key', 0: 'partner_name'}, inplace=True)
# partners_tbl

In [9]:
program_series = programs['Program Series'].copy()
program_series.replace(0, 'none', inplace=True)
program_series_type = program_series.unique()
program_series_type
new_program_series = {
    'PS': 'Physical Science',
    'SS': 'Science and Society', 
    'CEE': 'Climate, Energy, and Environment', 
    'LS': 'Life Science',
    'HS': 'Health and Wellness',
    'TEI': 'Technology and Engineering'
}
program_series_tbl = pd.DataFrame.from_dict(new_program_series, orient='index')
program_series_tbl.reset_index(inplace=True)
program_series_tbl.rename(columns={'index': 'series', 0: 'series_name'}, inplace=True)
program_series_tbl

  series                       series_name
0     PS                  Physical Science
1     SS               Science and Society
2    CEE  Climate, Energy, and Environment
3     LS                      Life Science
4     HS               Health and Wellness
5    TEI        Technology and Engineering

In [10]:
venues = programs['Venue'].copy()
new_venues = []
for venue in venues.values:
    new_venue = venue.strip().lower()
    new_venues.append(new_venue)
new_venues = pd.Series(new_venues)
new_venues = new_venues.unique()
new_venues_tbl = pd.DataFrame(pd.Series(new_venues))
new_venues_tbl.reset_index(inplace=True)
new_venues_tbl.rename(columns={'index': 'venue_key', 0: 'venue_name'}, inplace=True)
new_venues_tbl

     venue_key                          venue_name
0            0                           nu thorne
1            1          co-sponsor - all day event
2            2                     cultural center
3            3                   exelon/co-sponsor
4            4      adler planetarium/co - sponsor
..         ...                                 ...
132        132      northwestern prentice hospital
133        133                       facebook live
134        134  website (recorded - embedded link)
135        135             facebook live & youtube
136        136                               booth

[137 rows x 2 columns]

In [12]:
program_types_dict = {
    '1': 'original',
    '2': 'signature',
    '3': 'speakeasy',
    '4': 'booth',
    '5': 'local'
}

In [13]:
program_type_tbl = pd.DataFrame.from_dict(program_types_dict, orient='index')
program_type_tbl.reset_index(inplace=True)
program_type_tbl.rename(columns={'index': 'program_type_key', 0: 'program_type'}, inplace=True)
program_type_tbl

  program_type_key program_type
0                1     original
1                2    signature
2                3    speakeasy
3                4        booth
4                5        local

In [14]:
dates = programs['Date'].values
dates

array(['10/5/07', '10/29/07', '2/22/08', '3/12/08', '5/5&7/08', '9/24/08',
       '10/10/08', '10/14/08', '11/3/08', '11/20/08', '12/10/08',
       '1/20/09', '1/26/09', '2/15/09', '3/14/09', '4/22/09', '5/21/09',
       '6/8/09', '9/18/09', '10/14/09', '10/22/09', '10/26/09',
       '10/28/09', '11/12/09', '12/2/09', '12/6/09', '2/18/10', '3/11/10',
       '3/31/10', '4/6/10', '4/17/10', '4/21/10', '5/6/10', '6/5/10',
       '9/7/10', '9/21/10', '10/7/10', '11/16/10', '12/9/10', '1/25/11',
       '2/17/11', '2/24/11', '3/10/11', '4/16/11', '4/25/11', '4/27/11',
       '5/25/11', '8/5/11', '9/13/11', '9/24/11', '10/13/11', '11/13/11',
       '12/1/11', '1/19/12', '1/31/12', '2/11/12', '2/23/12', '3/16/12',
       '3/29/12', '4/19/12', '5/1/12', '5/12/12', '9/15/12', '9/20/12',
       '10/10/12', '10/11/12', '11/1/12', '11/8/12', '12/4/12', '1/25/13',
       '2/21/13', '2/23/13', '2/23/13', '3/7/13', '3/13/13', '3/21/13',
       '4/3/13', '8/1/13', '8/2/13', '9/10/13', '9/24/13', '10/24/13',
       '10/29/13', '11/12/13', '11/13/13', '12/11/13', '1/22/14',
       '1/30/14', '2/26/14', '3/12/14', '4/2/14', '4/3/14', '4/30/14',
       '8/23/14', '9/8/14', '9/19/14', '9/20/14', '10/21/14', '10/29/14',
       '11/12/14', '11/17/14', '11/20/14', '12/3/14', '12/9/14', '2/3/15',
       '2/3/15', '2/5/15', '2/11/15', '2/12/15', '2/21/15', '3/3/15',
       '3/12/15', '3/25/15', '4/7/15', '4/28/15', '5/4/15', '5/13/15',
       '6/2/15', '7/7/15', '7/21/15', '8/4/15', '8/18/15', '9/1/15',
       '9/15/15', '10/1/15', '10/6/15', '10/7/15', '10/20/15', '10/21/15',
       '11/3/15', '11/12/15', '11/17/15', '12/1/15', '12/1/15',
       '12/15/15', '1/5/16', '1/19/16', '2/2/16', '2/16/16', '2/25/16',
       '3/2/16', '3/9/16', '3/15/16', '3/23/16', '3/31/16', '4/9/16',
       '6/6/16', '6/11/16', '7/5/16', '8/2/16', '8/17/16', '9/6/16',
       '9/28/16', '10/4/16', '10/6/16', '10/27/16', '11/17/16',
       '12/06/16', '01/10/17', '01/28/17', '02/06/17', '02/07/17',
       '02/09/17', '03/07/17', '03/22/17', '03/30/17', '04/06/17',
       '04/11/17', '04/20/17', '04/22/17', '04/23/17', '04/24/17',
       '05/02/17', '05/04/17', '05/10/17', '06/12/17', '06/20/17',
       '07/11/17', '08/25/17', '09/06/17', '09/12/17', '09/23/17',
       '09/26/17', '10/10/17', '10/12/17', '11/13/17', '11/15/17',
       '12/12/17', '12/14/17', '01/16/18', '02/06/18', '02/20/18',
       '03/15/18', '03/19/18', '03/23/18', '04/04/18', '04/04/18',
       '04/05/18', '04/12/18', '04/14/18', '04/20/18', '04/22/18',
       '05/07/18', '05/10/18', '05/23/18', '06/07/18', '06/12/18',
       '06/14/18', '06/16/18', '08/15/18', '09/25/18', '09/27/18',
       '10/02/18', '10/10/18', '11/08/18', '11/09/18', '11/12/18',
       '11/28/18', '12/05/18', '12/12/18', '02/06/19', '02/20/19',
       '02/27/19', '02/28/19', '03/12/19', '03/21/19', '03/31/19',
       '04/03/19', '04/09/19', '04/17/19', '04/26/19', '05/09/19',
       '05/11/19', '05/16/19', '05/30/19', '06/11/19', '07/23/19',
       '08/22/19', '08/27/19', '09/11/19', '9/13/19', '09/25/19',
       '09/26/19', '10/05/19', '10/16/19', '10/17/19', '11/01/19',
       '11/13/19', '11/21/19', '12/06/19', '12/10/19', '01/27/20',
       '01/29/20', '01/29/20', '02/22/20', '02/29/20', '03/10/20',
       '04/07/20', '04/09/20', '04/16/20', '04/28/20', '05/07/20',
       '05/20/20', '05/26/20', '06/02/20', '06/17/20', '06/25/20',
       '06/30/20', '07/02/20', '07/09/20', '07/21/20', '08/05/20',
       '08/20/20', '08/27/20', '09/01/20', '09/24/20', '10/12/20'],
      dtype=object)

In [15]:
new_dates = []
for date in dates:
    new_date = date.replace('/', '-').split('-')#.replace('&', 'and')
    date_dict = {'month': new_date[0], 'day': new_date[1], 'year': new_date[2]}
    new_dates.append(date_dict)

In [16]:
for date in new_dates:
    for k,v in date.items():
        if k == 'month':
            if len(v) < 2:
                date[k] = '0' + v
        if k == 'day':
            if len(v) < 2:
                date[k] = '0' + v
            elif '&' in v:
                new_day = v.split('&')
                date[k] = new_day
new_dates

[{'day': '05', 'month': '10', 'year': '07'},
 {'day': '29', 'month': '10', 'year': '07'},
 {'day': '22', 'month': '02', 'year': '08'},
 {'day': '12', 'month': '03', 'year': '08'},
 {'day': ['5', '7'], 'month': '05', 'year': '08'},
 {'day': '24', 'month': '09', 'year': '08'},
 {'day': '10', 'month': '10', 'year': '08'},
 {'day': '14', 'month': '10', 'year': '08'},
 {'day': '03', 'month': '11', 'year': '08'},
 {'day': '20', 'month': '11', 'year': '08'},
 {'day': '10', 'month': '12', 'year': '08'},
 {'day': '20', 'month': '01', 'year': '09'},
 {'day': '26', 'month': '01', 'year': '09'},
 {'day': '15', 'month': '02', 'year': '09'},
 {'day': '14', 'month': '03', 'year': '09'},
 {'day': '22', 'month': '04', 'year': '09'},
 {'day': '21', 'month': '05', 'year': '09'},
 {'day': '08', 'month': '06', 'year': '09'},
 {'day': '18', 'month': '09', 'year': '09'},
 {'day': '14', 'month': '10', 'year': '09'},
 {'day': '22', 'month': '10', 'year': '09'},
 {'day': '26', 'month': '10', 'year': '09'},
 {'day': '28', 'month': '10', 'year': '09'},
 {'day': '12', 'month': '11', 'year': '09'},
 {'day': '02', 'month': '12', 'year': '09'},
 {'day': '06', 'month': '12', 'year': '09'},
 {'day': '18', 'month': '02', 'year': '10'},
 {'day': '11', 'month': '03', 'year': '10'},
 {'day': '31', 'month': '03', 'year': '10'},
 {'day': '06', 'month': '04', 'year': '10'},
 {'day': '17', 'month': '04', 'year': '10'},
 {'day': '21', 'month': '04', 'year': '10'},
 {'day': '06', 'month': '05', 'year': '10'},
 {'day': '05', 'month': '06', 'year': '10'},
 {'day': '07', 'month': '09', 'year': '10'},
 {'day': '21', 'month': '09', 'year': '10'},
 {'day': '07', 'month': '10', 'year': '10'},
 {'day': '16', 'month': '11', 'year': '10'},
 {'day': '09', 'month': '12', 'year': '10'},
 {'day': '25', 'month': '01', 'year': '11'},
 {'day': '17', 'month': '02', 'year': '11'},
 {'day': '24', 'month': '02', 'year': '11'},
 {'day': '10', 'month': '03', 'year': '11'},
 {'day': '16', 'month': '04', 'year': '11'},
 {'day': '25', 'month': '04', 'year': '11'},
 {'day': '27', 'month': '04', 'year': '11'},
 {'day': '25', 'month': '05', 'year': '11'},
 {'day': '05', 'month': '08', 'year': '11'},
 {'day': '13', 'month': '09', 'year': '11'},
 {'day': '24', 'month': '09', 'year': '11'},
 {'day': '13', 'month': '10', 'year': '11'},
 {'day': '13', 'month': '11', 'year': '11'},
 {'day': '01', 'month': '12', 'year': '11'},
 {'day': '19', 'month': '01', 'year': '12'},
 {'day': '31', 'month': '01', 'year': '12'},
 {'day': '11', 'month': '02', 'year': '12'},
 {'day': '23', 'month': '02', 'year': '12'},
 {'day': '16', 'month': '03', 'year': '12'},
 {'day': '29', 'month': '03', 'year': '12'},
 {'day': '19', 'month': '04', 'year': '12'},
 {'day': '01', 'month': '05', 'year': '12'},
 {'day': '12', 'month': '05', 'year': '12'},
 {'day': '15', 'month': '09', 'year': '12'},
 {'day': '20', 'month': '09', 'year': '12'},
 {'day': '10', 'month': '10', 'year': '12'},
 {'day': '11', 'month': '10', 'year': '12'},
 {'day': '01', 'month': '11', 'year': '12'},
 {'day': '08', 'month': '11', 'year': '12'},
 {'day': '04', 'month': '12', 'year': '12'},
 {'day': '25', 'month': '01', 'year': '13'},
 {'day': '21', 'month': '02', 'year': '13'},
 {'day': '23', 'month': '02', 'year': '13'},
 {'day': '23', 'month': '02', 'year': '13'},
 {'day': '07', 'month': '03', 'year': '13'},
 {'day': '13', 'month': '03', 'year': '13'},
 {'day': '21', 'month': '03', 'year': '13'},
 {'day': '03', 'month': '04', 'year': '13'},
 {'day': '01', 'month': '08', 'year': '13'},
 {'day': '02', 'month': '08', 'year': '13'},
 {'day': '10', 'month': '09', 'year': '13'},
 {'day': '24', 'month': '09', 'year': '13'},
 {'day': '24', 'month': '10', 'year': '13'},
 {'day': '29', 'month': '10', 'year': '13'},
 {'day': '12', 'month': '11', 'year': '13'},
 {'day': '13', 'month': '11', 'year': '13'},
 {'day': '11', 'month': '12', 'year': '13'},
 {'day': '22', 'month': '01', 'year': '14'},
 {'day': '30', 'month': '01', 'year': '14'},
 {'day': '26', 'month': '02', 'year': '14'},
 {'day': '12', 'month': '03', 'year': '14'},
 {'day': '02', 'month': '04', 'year': '14'},
 {'day': '03', 'month': '04', 'year': '14'},
 {'day': '30', 'month': '04', 'year': '14'},
 {'day': '23', 'month': '08', 'year': '14'},
 {'day': '08', 'month': '09', 'year': '14'},
 {'day': '19', 'month': '09', 'year': '14'},
 {'day': '20', 'month': '09', 'year': '14'},
 {'day': '21', 'month': '10', 'year': '14'},
 {'day': '29', 'month': '10', 'year': '14'},
 {'day': '12', 'month': '11', 'year': '14'},
 {'day': '17', 'month': '11', 'year': '14'},
 {'day': '20', 'month': '11', 'year': '14'},
 {'day': '03', 'month': '12', 'year': '14'},
 {'day': '09', 'month': '12', 'year': '14'},
 {'day': '03', 'month': '02', 'year': '15'},
 {'day': '03', 'month': '02', 'year': '15'},
 {'day': '05', 'month': '02', 'year': '15'},
 {'day': '11', 'month': '02', 'year': '15'},
 {'day': '12', 'month': '02', 'year': '15'},
 {'day': '21', 'month': '02', 'year': '15'},
 {'day': '03', 'month': '03', 'year': '15'},
 {'day': '12', 'month': '03', 'year': '15'},
 {'day': '25', 'month': '03', 'year': '15'},
 {'day': '07', 'month': '04', 'year': '15'},
 {'day': '28', 'month': '04', 'year': '15'},
 {'day': '04', 'month': '05', 'year': '15'},
 {'day': '13', 'month': '05', 'year': '15'},
 {'day': '02', 'month': '06', 'year': '15'},
 {'day': '07', 'month': '07', 'year': '15'},
 {'day': '21', 'month': '07', 'year': '15'},
 {'day': '04', 'month': '08', 'year': '15'},
 {'day': '18', 'month': '08', 'year': '15'},
 {'day': '01', 'month': '09', 'year': '15'},
 {'day': '15', 'month': '09', 'year': '15'},
 {'day': '01', 'month': '10', 'year': '15'},
 {'day': '06', 'month': '10', 'year': '15'},
 {'day': '07', 'month': '10', 'year': '15'},
 {'day': '20', 'month': '10', 'year': '15'},
 {'day': '21', 'month': '10', 'year': '15'},
 {'day': '03', 'month': '11', 'year': '15'},
 {'day': '12', 'month': '11', 'year': '15'},
 {'day': '17', 'month': '11', 'year': '15'},
 {'day': '01', 'month': '12', 'year': '15'},
 {'day': '01', 'month': '12', 'year': '15'},
 {'day': '15', 'month': '12', 'year': '15'},
 {'day': '05', 'month': '01', 'year': '16'},
 {'day': '19', 'month': '01', 'year': '16'},
 {'day': '02', 'month': '02', 'year': '16'},
 {'day': '16', 'month': '02', 'year': '16'},
 {'day': '25', 'month': '02', 'year': '16'},
 {'day': '02', 'month': '03', 'year': '16'},
 {'day': '09', 'month': '03', 'year': '16'},
 {'day': '15', 'month': '03', 'year': '16'},
 {'day': '23', 'month': '03', 'year': '16'},
 {'day': '31', 'month': '03', 'year': '16'},
 {'day': '09', 'month': '04', 'year': '16'},
 {'day': '06', 'month': '06', 'year': '16'},
 {'day': '11', 'month': '06', 'year': '16'},
 {'day': '05', 'month': '07', 'year': '16'},
 {'day': '02', 'month': '08', 'year': '16'},
 {'day': '17', 'month': '08', 'year': '16'},
 {'day': '06', 'month': '09', 'year': '16'},
 {'day': '28', 'month': '09', 'year': '16'},
 {'day': '04', 'month': '10', 'year': '16'},
 {'day': '06', 'month': '10', 'year': '16'},
 {'day': '27', 'month': '10', 'year': '16'},
 {'day': '17', 'month': '11', 'year': '16'},
 {'day': '06', 'month': '12', 'year': '16'},
 {'day': '10', 'month': '01', 'year': '17'},
 {'day': '28', 'month': '01', 'year': '17'},
 {'day': '06', 'month': '02', 'year': '17'},
 {'day': '07', 'month': '02', 'year': '17'},
 {'day': '09', 'month': '02', 'year': '17'},
 {'day': '07', 'month': '03', 'year': '17'},
 {'day': '22', 'month': '03', 'year': '17'},
 {'day': '30', 'month': '03', 'year': '17'},
 {'day': '06', 'month': '04', 'year': '17'},
 {'day': '11', 'month': '04', 'year': '17'},
 {'day': '20', 'month': '04', 'year': '17'},
 {'day': '22', 'month': '04', 'year': '17'},
 {'day': '23', 'month': '04', 'year': '17'},
 {'day': '24', 'month': '04', 'year': '17'},
 {'day': '02', 'month': '05', 'year': '17'},
 {'day': '04', 'month': '05', 'year': '17'},
 {'day': '10', 'month': '05', 'year': '17'},
 {'day': '12', 'month': '06', 'year': '17'},
 {'day': '20', 'month': '06', 'year': '17'},
 {'day': '11', 'month': '07', 'year': '17'},
 {'day': '25', 'month': '08', 'year': '17'},
 {'day': '06', 'month': '09', 'year': '17'},
 {'day': '12', 'month': '09', 'year': '17'},
 {'day': '23', 'month': '09', 'year': '17'},
 {'day': '26', 'month': '09', 'year': '17'},
 {'day': '10', 'month': '10', 'year': '17'},
 {'day': '12', 'month': '10', 'year': '17'},
 {'day': '13', 'month': '11', 'year': '17'},
 {'day': '15', 'month': '11', 'year': '17'},
 {'day': '12', 'month': '12', 'year': '17'},
 {'day': '14', 'month': '12', 'year': '17'},
 {'day': '16', 'month': '01', 'year': '18'},
 {'day': '06', 'month': '02', 'year': '18'},
 {'day': '20', 'month': '02', 'year': '18'},
 {'day': '15', 'month': '03', 'year': '18'},
 {'day': '19', 'month': '03', 'year': '18'},
 {'day': '23', 'month': '03', 'year': '18'},
 {'day': '04', 'month': '04', 'year': '18'},
 {'day': '04', 'month': '04', 'year': '18'},
 {'day': '05', 'month': '04', 'year': '18'},
 {'day': '12', 'month': '04', 'year': '18'},
 {'day': '14', 'month': '04', 'year': '18'},
 {'day': '20', 'month': '04', 'year': '18'},
 {'day': '22', 'month': '04', 'year': '18'},
 {'day': '07', 'month': '05', 'year': '18'},
 {'day': '10', 'month': '05', 'year': '18'},
 {'day': '23', 'month': '05', 'year': '18'},
 {'day': '07', 'month': '06', 'year': '18'},
 {'day': '12', 'month': '06', 'year': '18'},
 {'day': '14', 'month': '06', 'year': '18'},
 {'day': '16', 'month': '06', 'year': '18'},
 {'day': '15', 'month': '08', 'year': '18'},
 {'day': '25', 'month': '09', 'year': '18'},
 {'day': '27', 'month': '09', 'year': '18'},
 {'day': '02', 'month': '10', 'year': '18'},
 {'day': '10', 'month': '10', 'year': '18'},
 {'day': '08', 'month': '11', 'year': '18'},
 {'day': '09', 'month': '11', 'year': '18'},
 {'day': '12', 'month': '11', 'year': '18'},
 {'day': '28', 'month': '11', 'year': '18'},
 {'day': '05', 'month': '12', 'year': '18'},
 {'day': '12', 'month': '12', 'year': '18'},
 {'day': '06', 'month': '02', 'year': '19'},
 {'day': '20', 'month': '02', 'year': '19'},
 {'day': '27', 'month': '02', 'year': '19'},
 {'day': '28', 'month': '02', 'year': '19'},
 {'day': '12', 'month': '03', 'year': '19'},
 {'day': '21', 'month': '03', 'year': '19'},
 {'day': '31', 'month': '03', 'year': '19'},
 {'day': '03', 'month': '04', 'year': '19'},
 {'day': '09', 'month': '04', 'year': '19'},
 {'day': '17', 'month': '04', 'year': '19'},
 {'day': '26', 'month': '04', 'year': '19'},
 {'day': '09', 'month': '05', 'year': '19'},
 {'day': '11', 'month': '05', 'year': '19'},
 {'day': '16', 'month': '05', 'year': '19'},
 {'day': '30', 'month': '05', 'year': '19'},
 {'day': '11', 'month': '06', 'year': '19'},
 {'day': '23', 'month': '07', 'year': '19'},
 {'day': '22', 'month': '08', 'year': '19'},
 {'day': '27', 'month': '08', 'year': '19'},
 {'day': '11', 'month': '09', 'year': '19'},
 {'day': '13', 'month': '09', 'year': '19'},
 {'day': '25', 'month': '09', 'year': '19'},
 {'day': '26', 'month': '09', 'year': '19'},
 {'day': '05', 'month': '10', 'year': '19'},
 {'day': '16', 'month': '10', 'year': '19'},
 {'day': '17', 'month': '10', 'year': '19'},
 {'day': '01', 'month': '11', 'year': '19'},
 {'day': '13', 'month': '11', 'year': '19'},
 {'day': '21', 'month': '11', 'year': '19'},
 {'day': '06', 'month': '12', 'year': '19'},
 {'day': '10', 'month': '12', 'year': '19'},
 {'day': '27', 'month': '01', 'year': '20'},
 {'day': '29', 'month': '01', 'year': '20'},
 {'day': '29', 'month': '01', 'year': '20'},
 {'day': '22', 'month': '02', 'year': '20'},
 {'day': '29', 'month': '02', 'year': '20'},
 {'day': '10', 'month': '03', 'year': '20'},
 {'day': '07', 'month': '04', 'year': '20'},
 {'day': '09', 'month': '04', 'year': '20'},
 {'day': '16', 'month': '04', 'year': '20'},
 {'day': '28', 'month': '04', 'year': '20'},
 {'day': '07', 'month': '05', 'year': '20'},
 {'day': '20', 'month': '05', 'year': '20'},
 {'day': '26', 'month': '05', 'year': '20'},
 {'day': '02', 'month': '06', 'year': '20'},
 {'day': '17', 'month': '06', 'year': '20'},
 {'day': '25', 'month': '06', 'year': '20'},
 {'day': '30', 'month': '06', 'year': '20'},
 {'day': '02', 'month': '07', 'year': '20'},
 {'day': '09', 'month': '07', 'year': '20'},
 {'day': '21', 'month': '07', 'year': '20'},
 {'day': '05', 'month': '08', 'year': '20'},
 {'day': '20', 'month': '08', 'year': '20'},
 {'day': '27', 'month': '08', 'year': '20'},
 {'day': '01', 'month': '09', 'year': '20'},
 {'day': '24', 'month': '09', 'year': '20'},
 {'day': '12', 'month': '10', 'year': '20'}]

In [17]:
dates_df = pd.DataFrame.from_dict(new_dates)
programs = pd.merge(programs, dates_df, left_index=True, right_index=True)

In [19]:
energy_colloquium = programs.iloc[4].copy()
energy_colloquium
energy_colloquium1 = {
    'Date': '05-05-08',
    'Program Title': 'Energy Colloquium (Day 1)',
    'Live Stream': 0,
    'Attendance (in seats)': 60,
    'Hours': 1.5,
    'Program Series': 'CEE',
    'Venue': 'Exelon/Co-Sponsor',
    'Type of Program': 'Original', 
    'Male Speakers': 0,
    'Female Speakers': 0,
    'People of Color (informal)': 0,
    'Partner/ event': 'none',
    'month': '05',
    'day': '05',
    'year': '08'
}
energy_colloquium2 = {
    'Date': '05-07-08',
    'Program Title': 'Energy Colloquium (Day 2)',
    'Live Stream': 0,
    'Attendance (in seats)': 60,
    'Hours': 1.5,
    'Program Series': 'CEE',
    'Venue': 'Exelon/Co-Sponsor',
    'Type of Program': 'Original', 
    'Male Speakers': 0,
    'Female Speakers': 0,
    'People of Color (informal)': 0,
    'Partner/ event': 'none',
    'month': '05',
    'day': '07',
    'year': '08'
}
energy_colloquium = [energy_colloquium1, energy_colloquium2]
#programs.drop(labels=[4], axis=0, inplace=True)
#programs = programs.append(energy_colloquium, ignore_index=True)
programs.tail(10)

         Date                                      Program Title  ... day year
268  07/09/20       SFTF: Engineering at the Service of Humanity  ...  09   20
269  07/21/20  3D Printing in Action: An Introduction to Digi...  ...  21   20
270  08/05/20  Mindfully Coping: Strategies for Children and ...  ...  05   20
271  08/20/20  The Study of Ancient DNA: Knowledge from Unexp...  ...  20   20
272  08/27/20            Lessons in Biology Taught by a Pathogen  ...  27   20
273  09/01/20                               UIC Involvement Fair  ...  01   20
274  09/24/20  The Power of Genomics: Optimzing Health Outcom...  ...  24   20
275  10/12/20           Deploying SHIELD: To Illinois and Beyond  ...  12   20
276  05-05-08                          Energy Colloquium (Day 1)  ...  05   08
277  05-07-08                          Energy Colloquium (Day 2)  ...  07   08

[10 rows x 15 columns]

In [20]:
months = programs['month'].values
days = programs['day'].values
years = programs['year'].values
series_ls = programs['Program Series'].values
len(series_ls)

278

In [21]:
program_ids = []
for i in range(len(months)): 
    program_id = str(months[i]) + str(days[i]) + str(years[i]) + '-' + str(series_ls[i])
    program_ids.append(program_id)
    i += 1
programs['ProgramID'] = pd.Series(program_ids)
programs

         Date  ...   ProgramID
0     10/5/07  ...   100507-PS
1    10/29/07  ...   102907-PS
2     2/22/08  ...   022208-SS
3     3/12/08  ...   031208-SS
4     9/24/08  ...   092408-SS
..        ...  ...         ...
273  09/01/20  ...   090120-SS
274  09/24/20  ...   092420-LS
275  10/12/20  ...   101220-HW
276  05-05-08  ...  050508-CEE
277  05-07-08  ...  050708-CEE

[278 rows x 16 columns]

In [23]:
new_programs = programs[['ProgramID', 'month', 'day', 'year', 'Program Title', 'Program Series', 'Type of Program', 'Venue', 'Partner/ event','Hours', 'Attendance (in seats)', 'Live Stream', 'Male Speakers', 'Female Speakers', 'People of Color (informal)']]
new_programs

      ProgramID month  ... Female Speakers People of Color (informal)
0     100507-PS    10  ...               0                          0
1     102907-PS    10  ...               0                          0
2     022208-SS    02  ...               0                          0
3     031208-SS    03  ...               0                          0
4     092408-SS    09  ...               0                          0
..          ...   ...  ...             ...                        ...
273   090120-SS    09  ...               2                          0
274   092420-LS    09  ...               0                          0
275   101220-HW    10  ...               0                          0
276  050508-CEE    05  ...               0                          0
277  050708-CEE    05  ...               0                          0

[278 rows x 15 columns]

In [25]:
new_programs.groupby('Program Series').size()

Program Series
0       1
CEE    43
HW     34
LS     52
PS     32
SS     86
TEI    30
dtype: int64

## Youtube

In [98]:
youtube

           Video  ... Impressions click-through rate (%)
0          Total  ...                               3.23
1    7ZStUcT47Wo  ...                               4.49
2    FjJCJY8TfIU  ...                               7.95
3    bl2iGoOzB4o  ...                               4.66
4    K6fK_LIcDGE  ...                               8.35
..           ...  ...                                ...
269  H3ZVLksBgg0  ...                               1.80
270  IYiw4PyLqTg  ...                               0.21
271  Ozc_WGCcIGY  ...                               1.20
272  PnQhLb6EvKw  ...                               0.32
273  R1Pqri0rTJY  ...                               0.00

[274 rows x 8 columns]

In [102]:
#youtube.drop(0, inplace=True)
youtube.head(25)

          Video  ... Impressions click-through rate (%)
1   7ZStUcT47Wo  ...                               4.49
2   FjJCJY8TfIU  ...                               7.95
3   bl2iGoOzB4o  ...                               4.66
4   K6fK_LIcDGE  ...                               8.35
5   xt2wDYDLsx8  ...                               3.90
6   OzWgQOohnPQ  ...                               8.13
7   br8bKAZQf4s  ...                               4.76
8   zq6kgV1eoj4  ...                               3.51
9   GMjPSgtbYcM  ...                               2.05
10  jVXIX9jc3dw  ...                               3.83
11  LOnT_KfaIe0  ...                               3.28
12  remxHrVqlIE  ...                               7.29
13  DU0QI2kspUI  ...                               0.77
14  xGhAFt6Rnno  ...                               2.32
15  kd5qIL3NiXw  ...                               2.96
16  n7Zo80_zIKI  ...                               1.86
17  icgYtMYc_l0  ...                               5.11
18  gsryRHogZak  ...                               5.67
19  x2LYZul94wQ  ...                               3.45
20  31PpqzuUQRA  ...                               3.81
21  zwNwtWWvsJw  ...                               3.36
22  cNOWIBUlrHM  ...                               6.24
23  n0jaEmeQujQ  ...                               3.07
24  f-iEGz-81Z4  ...                               3.68
25  wSAW19RkjYY  ...                               2.66

[25 rows x 8 columns]

In [159]:
months_dict = {
    'jan': '01',
    'feb': '02', 
    'mar': '03',
    'apr': '04', 
    'may': '05',
    'jun': '06',
    'jul': '07',
    'aug': '08',
    'sep': '09',
    'oct': '10',
    'nov': '11',
    'dec': '12'
}

In [129]:
yt_dates = youtube['Video publish time'].values
yt_dates

new_yt_dates_dicts = []
for date in yt_dates:
    new_date = date.lower().strip(',').split(' ')
    date_dict = {'month': new_date[0], 'day': new_date[1].strip(','), 'year': new_date[2]}
    new_yt_dates_dicts.append(date_dict)
new_yt_dates_dicts

[{'day': '13', 'month': 'sep', 'year': '2014'},
 {'day': '13', 'month': 'aug', 'year': '2012'},
 {'day': '24', 'month': 'mar', 'year': '2016'},
 {'day': '12', 'month': 'oct', 'year': '2016'},
 {'day': '12', 'month': 'sep', 'year': '2017'},
 {'day': '29', 'month': 'sep', 'year': '2016'},
 {'day': '18', 'month': 'aug', 'year': '2016'},
 {'day': '18', 'month': 'jun', 'year': '2018'},
 {'day': '2', 'month': 'jul', 'year': '2020'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '12', 'month': 'apr', 'year': '2017'},
 {'day': '4', 'month': 'oct', 'year': '2018'},
 {'day': '15', 'month': 'apr', 'year': '2016'},
 {'day': '6', 'month': 'dec', 'year': '2015'},
 {'day': '21', 'month': 'feb', 'year': '2018'},
 {'day': '27', 'month': 'jun', 'year': '2017'},
 {'day': '3', 'month': 'dec', 'year': '2015'},
 {'day': '19', 'month': 'oct', 'year': '2015'},
 {'day': '21', 'month': 'apr', 'year': '2017'},
 {'day': '13', 'month': 'oct', 'year': '2017'},
 {'day': '10', 'month': 'jan', 'year': '2020'},
 {'day': '18', 'month': 'sep', 'year': '2017'},
 {'day': '31', 'month': 'jan', 'year': '2012'},
 {'day': '19', 'month': 'apr', 'year': '2017'},
 {'day': '13', 'month': 'sep', 'year': '2014'},
 {'day': '31', 'month': 'jan', 'year': '2018'},
 {'day': '11', 'month': 'mar', 'year': '2013'},
 {'day': '27', 'month': 'oct', 'year': '2018'},
 {'day': '12', 'month': 'nov', 'year': '2013'},
 {'day': '31', 'month': 'mar', 'year': '2017'},
 {'day': '11', 'month': 'mar', 'year': '2016'},
 {'day': '20', 'month': 'aug', 'year': '2020'},
 {'day': '11', 'month': 'nov', 'year': '2015'},
 {'day': '23', 'month': 'jan', 'year': '2019'},
 {'day': '2', 'month': 'may', 'year': '2012'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '9', 'month': 'may', 'year': '2012'},
 {'day': '1', 'month': 'jul', 'year': '2020'},
 {'day': '26', 'month': 'jun', 'year': '2020'},
 {'day': '16', 'month': 'sep', 'year': '2014'},
 {'day': '27', 'month': 'oct', 'year': '2018'},
 {'day': '25', 'month': 'oct', 'year': '2019'},
 {'day': '11', 'month': 'apr', 'year': '2017'},
 {'day': '3', 'month': 'jun', 'year': '2014'},
 {'day': '26', 'month': 'apr', 'year': '2017'},
 {'day': '5', 'month': 'may', 'year': '2019'},
 {'day': '24', 'month': 'may', 'year': '2018'},
 {'day': '18', 'month': 'apr', 'year': '2017'},
 {'day': '4', 'month': 'dec', 'year': '2015'},
 {'day': '21', 'month': 'jun', 'year': '2012'},
 {'day': '6', 'month': 'dec', 'year': '2013'},
 {'day': '21', 'month': 'oct', 'year': '2019'},
 {'day': '13', 'month': 'jul', 'year': '2017'},
 {'day': '9', 'month': 'sep', 'year': '2016'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '10', 'month': 'feb', 'year': '2015'},
 {'day': '26', 'month': 'aug', 'year': '2017'},
 {'day': '21', 'month': 'may', 'year': '2018'},
 {'day': '7', 'month': 'jun', 'year': '2012'},
 {'day': '15', 'month': 'may', 'year': '2019'},
 {'day': '9', 'month': 'dec', 'year': '2014'},
 {'day': '31', 'month': 'jan', 'year': '2014'},
 {'day': '9', 'month': 'jul', 'year': '2020'},
 {'day': '29', 'month': 'mar', 'year': '2018'},
 {'day': '26', 'month': 'jun', 'year': '2017'},
 {'day': '27', 'month': 'oct', 'year': '2018'},
 {'day': '23', 'month': 'jun', 'year': '2014'},
 {'day': '25', 'month': 'oct', 'year': '2019'},
 {'day': '18', 'month': 'sep', 'year': '2017'},
 {'day': '22', 'month': 'aug', 'year': '2018'},
 {'day': '18', 'month': 'jan', 'year': '2013'},
 {'day': '27', 'month': 'sep', 'year': '2012'},
 {'day': '19', 'month': 'nov', 'year': '2014'},
 {'day': '5', 'month': 'aug', 'year': '2020'},
 {'day': '18', 'month': 'nov', 'year': '2013'},
 {'day': '18', 'month': 'jun', 'year': '2020'},
 {'day': '17', 'month': 'sep', 'year': '2014'},
 {'day': '27', 'month': 'may', 'year': '2020'},
 {'day': '1', 'month': 'nov', 'year': '2017'},
 {'day': '10', 'month': 'dec', 'year': '2014'},
 {'day': '21', 'month': 'jul', 'year': '2020'},
 {'day': '27', 'month': 'aug', 'year': '2020'},
 {'day': '15', 'month': 'oct', 'year': '2018'},
 {'day': '3', 'month': 'jun', 'year': '2020'},
 {'day': '13', 'month': 'jan', 'year': '2014'},
 {'day': '22', 'month': 'oct', 'year': '2019'},
 {'day': '9', 'month': 'mar', 'year': '2016'},
 {'day': '21', 'month': 'feb', 'year': '2015'},
 {'day': '5', 'month': 'may', 'year': '2017'},
 {'day': '5', 'month': 'may', 'year': '2015'},
 {'day': '3', 'month': 'jun', 'year': '2015'},
 {'day': '19', 'month': 'dec', 'year': '2015'},
 {'day': '7', 'month': 'dec', 'year': '2015'},
 {'day': '16', 'month': 'apr', 'year': '2018'},
 {'day': '21', 'month': 'apr', 'year': '2016'},
 {'day': '1', 'month': 'dec', 'year': '2017'},
 {'day': '17', 'month': 'jun', 'year': '2019'},
 {'day': '25', 'month': 'jun', 'year': '2018'},
 {'day': '23', 'month': 'may', 'year': '2019'},
 {'day': '10', 'month': 'jan', 'year': '2020'},
 {'day': '27', 'month': 'dec', 'year': '2017'},
 {'day': '8', 'month': 'dec', 'year': '2018'},
 {'day': '7', 'month': 'jan', 'year': '2019'},
 {'day': '11', 'month': 'dec', 'year': '2014'},
 {'day': '17', 'month': 'jun', 'year': '2019'},
 {'day': '2', 'month': 'oct', 'year': '2015'},
 {'day': '19', 'month': 'nov', 'year': '2014'},
 {'day': '27', 'month': 'oct', 'year': '2018'},
 {'day': '30', 'month': 'apr', 'year': '2012'},
 {'day': '14', 'month': 'apr', 'year': '2018'},
 {'day': '7', 'month': 'dec', 'year': '2017'},
 {'day': '5', 'month': 'dec', 'year': '2011'},
 {'day': '14', 'month': 'feb', 'year': '2019'},
 {'day': '17', 'month': 'jun', 'year': '2020'},
 {'day': '12', 'month': 'feb', 'year': '2019'},
 {'day': '10', 'month': 'mar', 'year': '2016'},
 {'day': '19', 'month': 'nov', 'year': '2014'},
 {'day': '24', 'month': 'oct', 'year': '2019'},
 {'day': '17', 'month': 'jun', 'year': '2019'},
 {'day': '15', 'month': 'oct', 'year': '2018'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '14', 'month': 'apr', 'year': '2014'},
 {'day': '29', 'month': 'mar', 'year': '2014'},
 {'day': '9', 'month': 'dec', 'year': '2017'},
 {'day': '26', 'month': 'nov', 'year': '2014'},
 {'day': '8', 'month': 'may', 'year': '2020'},
 {'day': '16', 'month': 'mar', 'year': '2018'},
 {'day': '19', 'month': 'nov', 'year': '2014'},
 {'day': '1', 'month': 'jan', 'year': '1970'},
 {'day': '21', 'month': 'oct', 'year': '2018'},
 {'day': '10', 'month': 'sep', 'year': '2012'},
 {'day': '8', 'month': 'feb', 'year': '2019'},
 {'day': '3', 'month': 'mar', 'year': '2019'},
 {'day': '24', 'month': 'aug', 'year': '2018'},
 {'day': '14', 'month': 'dec', 'year': '2016'},
 {'day': '8', 'month': 'may', 'year': '2019'},
 {'day': '1', 'month': 'may', 'year': '2019'},
 {'day': '11', 'month': 'nov', 'year': '2014'},
 {'day': '9', 'month': 'dec', 'year': '2011'},
 {'day': '31', 'month': 'mar', 'year': '2018'},
 {'day': '4', 'month': 'sep', 'year': '2020'},
 {'day': '12', 'month': 'oct', 'year': '2018'},
 {'day': '15', 'month': 'oct', 'year': '2018'},
 {'day': '4', 'month': 'mar', 'year': '2019'},
 {'day': '19', 'month': 'nov', 'year': '2014'},
 {'day': '27', 'month': 'apr', 'year': '2018'},
 {'day': '10', 'month': 'dec', 'year': '2014'},
 {'day': '5', 'month': 'dec', 'year': '2011'},
 {'day': '3', 'month': 'jan', 'year': '2019'},
 {'day': '15', 'month': 'may', 'year': '2020'},
 {'day': '15', 'month': 'feb', 'year': '2015'},
 {'day': '10', 'month': 'may', 'year': '2020'},
 {'day': '24', 'month': 'feb', 'year': '2015'},
 {'day': '3', 'month': 'oct', 'year': '2017'},
 {'day': '20', 'month': 'nov', 'year': '2017'},
 {'day': '28', 'month': 'nov', 'year': '2017'},
 {'day': '20', 'month': 'apr', 'year': '2015'},
 {'day': '20', 'month': 'may', 'year': '2015'},
 {'day': '23', 'month': 'feb', 'year': '2017'},
 {'day': '28', 'month': 'may', 'year': '2020'},
 {'day': '13', 'month': 'aug', 'year': '2012'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '28', 'month': 'dec', 'year': '2019'},
 {'day': '1', 'month': 'mar', 'year': '2019'},
 {'day': '5', 'month': 'may', 'year': '2015'},
 {'day': '2', 'month': 'jun', 'year': '2020'},
 {'day': '12', 'month': 'nov', 'year': '2013'},
 {'day': '28', 'month': 'mar', 'year': '2019'},
 {'day': '24', 'month': 'oct', 'year': '2019'},
 {'day': '11', 'month': 'apr', 'year': '2019'},
 {'day': '11', 'month': 'nov', 'year': '2019'},
 {'day': '10', 'month': 'dec', 'year': '2014'},
 {'day': '17', 'month': 'oct', 'year': '2019'},
 {'day': '9', 'month': 'dec', 'year': '2011'},
 {'day': '5', 'month': 'dec', 'year': '2011'},
 {'day': '25', 'month': 'sep', 'year': '2015'},
 {'day': '26', 'month': 'nov', 'year': '2014'},
 {'day': '16', 'month': 'oct', 'year': '2018'},
 {'day': '30', 'month': 'may', 'year': '2019'},
 {'day': '3', 'month': 'feb', 'year': '2012'},
 {'day': '20', 'month': 'oct', 'year': '2018'},
 {'day': '19', 'month': 'nov', 'year': '2014'},
 {'day': '21', 'month': 'oct', 'year': '2018'},
 {'day': '2', 'month': 'may', 'year': '2012'},
 {'day': '3', 'month': 'mar', 'year': '2019'},
 {'day': '15', 'month': 'dec', 'year': '2017'},
 {'day': '2', 'month': 'oct', 'year': '2018'},
 {'day': '10', 'month': 'dec', 'year': '2014'},
 {'day': '17', 'month': 'mar', 'year': '2019'},
 {'day': '14', 'month': 'may', 'year': '2020'},
 {'day': '23', 'month': 'may', 'year': '2014'},
 {'day': '3', 'month': 'apr', 'year': '2016'},
 {'day': '25', 'month': 'oct', 'year': '2019'},
 {'day': '9', 'month': 'dec', 'year': '2011'},
 {'day': '2', 'month': 'apr', 'year': '2015'},
 {'day': '1', 'month': 'mar', 'year': '2019'},
 {'day': '18', 'month': 'nov', 'year': '2013'},
 {'day': '9', 'month': 'dec', 'year': '2011'},
 {'day': '9', 'month': 'mar', 'year': '2016'},
 {'day': '30', 'month': 'jan', 'year': '2015'},
 {'day': '5', 'month': 'dec', 'year': '2019'},
 {'day': '4', 'month': 'dec', 'year': '2017'},
 {'day': '1', 'month': 'jul', 'year': '2020'},
 {'day': '2', 'month': 'may', 'year': '2019'},
 {'day': '25', 'month': 'jul', 'year': '2018'},
 {'day': '20', 'month': 'nov', 'year': '2017'},
 {'day': '31', 'month': 'jul', 'year': '2020'},
 {'day': '3', 'month': 'apr', 'year': '2017'},
 {'day': '27', 'month': 'mar', 'year': '2019'},
 {'day': '30', 'month': 'jan', 'year': '2015'},
 {'day': '15', 'month': 'may', 'year': '2019'},
 {'day': '18', 'month': 'jan', 'year': '2013'},
 {'day': '1', 'month': 'oct', 'year': '2018'},
 {'day': '5', 'month': 'aug', 'year': '2020'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '17', 'month': 'jun', 'year': '2019'},
 {'day': '19', 'month': 'nov', 'year': '2013'},
 {'day': '8', 'month': 'may', 'year': '2019'},
 {'day': '28', 'month': 'dec', 'year': '2019'},
 {'day': '19', 'month': 'feb', 'year': '2015'},
 {'day': '13', 'month': 'aug', 'year': '2012'},
 {'day': '15', 'month': 'may', 'year': '2017'},
 {'day': '9', 'month': 'mar', 'year': '2020'},
 {'day': '5', 'month': 'may', 'year': '2019'},
 {'day': '9', 'month': 'may', 'year': '2012'},
 {'day': '2', 'month': 'may', 'year': '2012'},
 {'day': '10', 'month': 'dec', 'year': '2014'},
 {'day': '19', 'month': 'nov', 'year': '2014'},
 {'day': '17', 'month': 'jun', 'year': '2019'},
 {'day': '5', 'month': 'mar', 'year': '2019'},
 {'day': '31', 'month': 'may', 'year': '2012'},
 {'day': '10', 'month': 'dec', 'year': '2014'},
 {'day': '11', 'month': 'jun', 'year': '2012'},
 {'day': '12', 'month': 'jun', 'year': '2014'},
 {'day': '4', 'month': 'aug', 'year': '2020'},
 {'day': '2', 'month': 'may', 'year': '2012'},
 {'day': '28', 'month': 'dec', 'year': '2019'},
 {'day': '3', 'month': 'oct', 'year': '2012'},
 {'day': '10', 'month': 'aug', 'year': '2012'},
 {'day': '18', 'month': 'nov', 'year': '2013'},
 {'day': '7', 'month': 'aug', 'year': '2020'},
 {'day': '18', 'month': 'nov', 'year': '2013'},
 {'day': '1', 'month': 'oct', 'year': '2012'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '10', 'month': 'dec', 'year': '2014'},
 {'day': '27', 'month': 'mar', 'year': '2019'},
 {'day': '9', 'month': 'dec', 'year': '2011'},
 {'day': '29', 'month': 'apr', 'year': '2016'},
 {'day': '23', 'month': 'aug', 'year': '2017'},
 {'day': '1', 'month': 'jan', 'year': '1970'},
 {'day': '24', 'month': 'feb', 'year': '2018'},
 {'day': '18', 'month': 'nov', 'year': '2013'},
 {'day': '9', 'month': 'dec', 'year': '2011'},
 {'day': '4', 'month': 'jun', 'year': '2012'},
 {'day': '10', 'month': 'aug', 'year': '2012'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '12', 'month': 'nov', 'year': '2013'},
 {'day': '9', 'month': 'jul', 'year': '2020'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '5', 'month': 'dec', 'year': '2011'},
 {'day': '19', 'month': 'dec', 'year': '2015'},
 {'day': '4', 'month': 'mar', 'year': '2019'},
 {'day': '12', 'month': 'sep', 'year': '2012'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '13', 'month': 'mar', 'year': '2013'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '10', 'month': 'feb', 'year': '2012'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '24', 'month': 'feb', 'year': '2015'},
 {'day': '10', 'month': 'dec', 'year': '2011'},
 {'day': '13', 'month': 'aug', 'year': '2015'},
 {'day': '7', 'month': 'nov', 'year': '2013'},
 {'day': '29', 'month': 'apr', 'year': '2015'}]

In [130]:
for date in new_yt_dates_dicts:
    for k,v in date.items():
        if k == 'day':
            if len(v) < 2:
                date[k] = '0' + v
        elif k == 'year':
            new_year = str(v)
            date[k] = new_year
        else:
            date[k] = v

In [155]:
new_yt_dates_dicts
new_yt_dates_df = pd.DataFrame.from_dict(new_yt_dates_dicts)
new_yt_dates_df.reset_index(inplace=True)
new_yt_dates_df

     index month day  year
0        0   sep  13  2014
1        1   aug  13  2012
2        2   mar  24  2016
3        3   oct  12  2016
4        4   sep  12  2017
..     ...   ...  ..   ...
268    268   feb  24  2015
269    269   dec  10  2011
270    270   aug  13  2015
271    271   nov  07  2013
272    272   apr  29  2015

[273 rows x 4 columns]

In [156]:
youtube_copy = youtube.copy().reset_index()
youtube_copy['index'] = youtube_copy['index'].apply(lambda x: x-1)
youtube_copy

     index        Video  ... Impressions Impressions click-through rate (%)
0        0  7ZStUcT47Wo  ...       87317                               4.49
1        1  FjJCJY8TfIU  ...       35696                               7.95
2        2  bl2iGoOzB4o  ...        6612                               4.66
3        3  K6fK_LIcDGE  ...       23115                               8.35
4        4  xt2wDYDLsx8  ...       41121                               3.90
..     ...          ...  ...         ...                                ...
268    268  H3ZVLksBgg0  ...         111                               1.80
269    269  IYiw4PyLqTg  ...         467                               0.21
270    270  Ozc_WGCcIGY  ...         166                               1.20
271    271  PnQhLb6EvKw  ...         315                               0.32
272    272  R1Pqri0rTJY  ...           1                               0.00

[273 rows x 9 columns]

In [157]:
yt_better_dates = pd.merge(youtube_copy, new_yt_dates_df, how='outer', on='index', indicator=True)
yt_better_dates

     index        Video  ...  year _merge
0        0  7ZStUcT47Wo  ...  2014   both
1        1  FjJCJY8TfIU  ...  2012   both
2        2  bl2iGoOzB4o  ...  2016   both
3        3  K6fK_LIcDGE  ...  2016   both
4        4  xt2wDYDLsx8  ...  2017   both
..     ...          ...  ...   ...    ...
268    268  H3ZVLksBgg0  ...  2015   both
269    269  IYiw4PyLqTg  ...  2011   both
270    270  Ozc_WGCcIGY  ...  2015   both
271    271  PnQhLb6EvKw  ...  2013   both
272    272  R1Pqri0rTJY  ...  2015   both

[273 rows x 13 columns]

In [163]:
yt_better_dates.replace({'month': months_dict}, inplace=True)
yt_better_dates

     index        Video  ...  year _merge
0        0  7ZStUcT47Wo  ...  2014   both
1        1  FjJCJY8TfIU  ...  2012   both
2        2  bl2iGoOzB4o  ...  2016   both
3        3  K6fK_LIcDGE  ...  2016   both
4        4  xt2wDYDLsx8  ...  2017   both
..     ...          ...  ...   ...    ...
268    268  H3ZVLksBgg0  ...  2015   both
269    269  IYiw4PyLqTg  ...  2011   both
270    270  Ozc_WGCcIGY  ...  2015   both
271    271  PnQhLb6EvKw  ...  2013   both
272    272  R1Pqri0rTJY  ...  2015   both

[273 rows x 13 columns]

In [ ]:
video

In [101]:
programs_yt = programs_tbl[['ProgramID', 'month', 'day', 'year', 'Program Title']].copy()
programs_yt

      ProgramID month  ... year                                      Program Title
0     100507-PS    10  ...   07                             Anniversary of Sputnik
1     102907-PS    10  ...   07                        Nasa Administrative Griffin
2     022208-SS    02  ...   08                                          Stem Cell
3     031208-SS    03  ...   08                          Future of Science: Rosner
4     092408-SS    09  ...   08                                       Alan Leshner
..          ...   ...  ...  ...                                                ...
273   090120-SS    09  ...   20                               UIC Involvement Fair
274   092420-LS    09  ...   20  The Power of Genomics: Optimzing Health Outcom...
275   101220-HW    10  ...   20           Deploying SHIELD: To Illinois and Beyond
276  050508-CEE    05  ...   08                          Energy Colloquium (Day 1)
277  050708-CEE    05  ...   08                          Energy Colloquium (Day 2)

[278 rows x 5 columns]

## Facebook

In [247]:
facebook = fb1.merge(fb2, how='outer')
facebook = facebook.merge(fb3, how='outer')
facebook = facebook.merge(fb4, how='outer')
facebook = facebook.merge(fb5, how='outer')
facebook.drop(0, inplace=True)
facebook

                             Post ID  ... Lifetime Talking About This (Post) by action type - share
1   163815626997995_2247842851928585  ...                                                NaN
2   163815626997995_2178121278900743  ...                                                NaN
3   163815626997995_2224957224217148  ...                                                NaN
4   163815626997995_2127857120593826  ...                                                NaN
5   163815626997995_2118764051503133  ...                                                NaN
6    163815626997995_567473160423691  ...                                               10.0
7    163815626997995_299896280911741  ...                                                8.0
8   163815626997995_2220058584707012  ...                                                NaN
9   163815626997995_2230106330368904  ...                                                NaN
10   163815626997995_333057674003003  ...                                                4.0
11   163815626997995_307786086550940  ...                                                NaN
12  163815626997995_2086407854738753  ...                                                NaN
13   163815626997995_445879205974812  ...                                                2.0
14  163815626997995_2158951957484342  ...                                                NaN
15  163815626997995_2188708107842060  ...                                                NaN
16  163815626997995_1039672012891508  ...                                                6.0
17  163815626997995_2074830022563203  ...                                                NaN
18  163815626997995_2125544884158383  ...                                                NaN
19   163815626997995_659993134518388  ...                                                9.0
20  163815626997995_1237015259788586  ...                                                1.0
21  163815626997995_2051144061598466  ...                                                NaN
22  163815626997995_2134502726595932  ...                                                NaN
23  163815626997995_2137176182995253  ...                                                NaN
24  163815626997995_2121538151225723  ...                                                NaN
25  163815626997995_2070446699668202  ...                                                3.0
26  163815626997995_2360857287293807  ...                                                NaN
27  163815626997995_2349306381782231  ...                                                NaN
28  163815626997995_2473183669394501  ...                                                NaN
29  163815626997995_2379531058759763  ...                                                NaN
30  163815626997995_2414672348578967  ...                                                NaN
31  163815626997995_2394687233910812  ...                                                NaN
32  163815626997995_2306334576079412  ...                                                NaN
33  163815626997995_2396871453692390  ...                                                NaN
34  163815626997995_2544941092218758  ...                                                NaN
35   163815626997995_442777316441180  ...                                                2.0
36  163815626997995_2660835784031583  ...                                               14.0
37   163815626997995_516966732370029  ...                                                3.0
38  163815626997995_1691772297631304  ...                                                2.0
39   163815626997995_545604132782615  ...                                                6.0
40   163815626997995_233548857988277  ...                                                5.0
41  163815626997995_1094969944203589  ...                                                3.0
42   163815626997995_577273266243327  ...                                               10.0
43   163815626997995_586122298677190  ...                                                1.0
44   163815626997995_238121774051017  ...                                                3.0
45   163815626997995_252822859161206  ...                                                1.0
46  163815626997995_3100209363358592  ...                                                NaN
47  163815626997995_3268804819832378  ...                                                NaN
48   163815626997995_955219121616822  ...                                                3.0
49   163815626997995_315939189682664  ...                                                1.0
50   163815626997995_341645600563706  ...                                                4.0
51   163815626997995_604032953849979  ...                                                3.0
52   163815626997995_274170123791143  ...                                                2.0
53  163815626997995_2700080293429895  ...                                                4.0
54   163815626997995_225096068458728  ...                                                3.0
55  163815626997995_3226448280734699  ...                                                NaN
56  163815626997995_2351117388522924  ...                                                2.0
57  163815626997995_3132922820119077  ...                                                2.0
58  163815626997995_3151439228235605  ...                                                NaN
59   163815626997995_328542921772260  ...                                                3.0
60  163815626997995_3233012440078283  ...                                                NaN

[60 rows x 171 columns]

In [248]:
fb = facebook[['Post ID', 'Permalink', 'Post Message', 'Type', 'Posted', 'Lifetime Post Total Impressions', 'Lifetime Total Video Views', 'Lifetime Unique Video Views']]
fb.head()

                            Post ID  ... Lifetime Unique Video Views
1  163815626997995_2247842851928585  ...                          25
2  163815626997995_2178121278900743  ...                          15
3  163815626997995_2224957224217148  ...                          34
4  163815626997995_2127857120593826  ...                         148
5  163815626997995_2118764051503133  ...                         139

[5 rows x 8 columns]

In [249]:
fb['Post Message'].fillna('[empty]', inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

In [255]:
fb['posted_split'] = fb.Posted.apply(lambda x: x.split(' '))
fb['posted_date'] = fb.posted_split.apply(lambda x: x[0])
fb['posted_time'] = fb.posted_split.apply(lambda x: x[1])
fb['posted_time_of_day'] = fb.posted_split.apply(lambda x: x[2])
fb.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

                            Post ID  ...                posted_split
1  163815626997995_2247842851928585  ...  [05/31/2019, 10:04:57, AM]
2  163815626997995_2178121278900743  ...  [04/17/2019, 02:44:21, PM]
3  163815626997995_2224957224217148  ...  [05/17/2019, 09:54:24, AM]
4  163815626997995_2127857120593826  ...  [03/13/2019, 08:10:35, AM]
5  163815626997995_2118764051503133  ...  [03/06/2019, 09:40:59, AM]

[5 rows x 12 columns]

In [310]:
fb_dates = fb.posted_date.values
new_fb_dates = []
for date in fb_dates:
    new_fb_date = date.replace('/', '-').split('-')#.replace('&', 'and')
    date_dict = {'month': new_fb_date[0], 'day': new_fb_date[1], 'year': new_fb_date[2]}
    new_fb_dates.append(date_dict)

fb_dates_df = pd.DataFrame.from_dict(new_fb_dates)
fb_dates_df.reset_index(inplace=True)
fb_dates_df['index'] = fb_dates_df['index'].apply(lambda x: x+1)
fb_dates_df

    index month day  year
0       1    05  31  2019
1       2    04  17  2019
2       3    05  17  2019
3       4    03  13  2019
4       5    03  06  2019
5       6    02  28  2019
6       7    02  06  2019
7       8    05  14  2019
8       9    05  20  2019
9      10    03  21  2019
10     11    04  03  2019
11     12    02  12  2019
12     13    05  30  2019
13     14    04  04  2019
14     15    04  24  2019
15     16    04  03  2019
16     17    02  04  2019
17     18    03  11  2019
18     19    06  11  2019
19     20    04  03  2019
20     21    01  18  2019
21     22    03  18  2019
22     23    03  20  2019
23     24    03  08  2019
24     25    02  01  2019
25     26    08  05  2019
26     27    07  29  2019
27     28    10  07  2019
28     29    08  16  2019
29     30    09  05  2019
30     31    08  25  2019
31     32    07  04  2019
32     33    08  26  2019
33     34    11  11  2019
34     35    11  21  2019
35     36    10  16  2019
36     37    09  25  2019
37     38    12  06  2019
38     39    06  02  2020
39     40    04  16  2020
40     41    04  07  2020
41     42    05  07  2020
42     43    05  20  2020
43     44    04  09  2020
44     45    05  26  2020
45     46    07  13  2020
46     47    09  09  2020
47     48    07  21  2020
48     49    08  27  2020
49     50    08  05  2020
50     51    07  09  2020
51     52    06  25  2020
52     53    06  17  2020
53     54    07  02  2020
54     55    08  26  2020
55     56    06  30  2020
56     57    08  20  2020
57     58    07  31  2020
58     59    09  24  2020
59     60    08  28  2020

In [306]:
fb_new_index = fb.copy().reset_index()
fb_new_index

    index  ...                posted_split
0       1  ...  [05/31/2019, 10:04:57, AM]
1       2  ...  [04/17/2019, 02:44:21, PM]
2       3  ...  [05/17/2019, 09:54:24, AM]
3       4  ...  [03/13/2019, 08:10:35, AM]
4       5  ...  [03/06/2019, 09:40:59, AM]
5       6  ...  [02/28/2019, 04:30:08, PM]
6       7  ...  [02/06/2019, 04:00:08, PM]
7       8  ...  [05/14/2019, 09:36:50, AM]
8       9  ...  [05/20/2019, 01:35:44, PM]
9      10  ...  [03/21/2019, 04:13:05, PM]
10     11  ...  [04/03/2019, 04:57:46, PM]
11     12  ...  [02/12/2019, 09:53:02, AM]
12     13  ...  [05/30/2019, 02:05:07, PM]
13     14  ...  [04/04/2019, 08:50:01, AM]
14     15  ...  [04/24/2019, 11:44:42, AM]
15     16  ...  [04/03/2019, 04:00:08, PM]
16     17  ...  [02/04/2019, 10:51:26, AM]
17     18  ...  [03/11/2019, 01:32:48, PM]
18     19  ...  [06/11/2019, 04:05:11, PM]
19     20  ...  [04/03/2019, 05:22:15, PM]
20     21  ...  [01/18/2019, 11:02:07, AM]
21     22  ...  [03/18/2019, 08:40:40, AM]
22     23  ...  [03/20/2019, 08:33:19, AM]
23     24  ...  [03/08/2019, 09:31:11, AM]
24     25  ...  [02/01/2019, 09:32:38, AM]
25     26  ...  [08/05/2019, 08:51:53, AM]
26     27  ...  [07/29/2019, 09:35:56, AM]
27     28  ...  [10/07/2019, 10:42:29, AM]
28     29  ...  [08/16/2019, 11:55:40, AM]
29     30  ...  [09/05/2019, 10:26:52, AM]
30     31  ...  [08/25/2019, 05:55:42, AM]
31     32  ...  [07/04/2019, 07:58:37, AM]
32     33  ...  [08/26/2019, 09:44:40, AM]
33     34  ...  [11/11/2019, 09:43:26, AM]
34     35  ...  [11/21/2019, 04:01:01, PM]
35     36  ...  [10/16/2019, 04:00:13, PM]
36     37  ...  [09/25/2019, 04:01:52, PM]
37     38  ...  [12/06/2019, 03:43:51, PM]
38     39  ...  [06/02/2020, 02:00:13, PM]
39     40  ...  [04/16/2020, 02:00:09, PM]
40     41  ...  [04/07/2020, 02:00:09, PM]
41     42  ...  [05/07/2020, 02:00:11, PM]
42     43  ...  [05/20/2020, 02:00:10, PM]
43     44  ...  [04/09/2020, 02:00:09, PM]
44     45  ...  [05/26/2020, 04:00:12, PM]
45     46  ...  [07/13/2020, 07:41:55, AM]
46     47  ...  [09/09/2020, 07:19:59, AM]
47     48  ...  [07/21/2020, 02:00:13, PM]
48     49  ...  [08/27/2020, 02:00:20, PM]
49     50  ...  [08/05/2020, 02:00:16, PM]
50     51  ...  [07/09/2020, 02:00:12, PM]
51     52  ...  [06/25/2020, 02:00:14, PM]
52     53  ...  [06/17/2020, 02:00:13, PM]
53     54  ...  [07/02/2020, 02:30:12, PM]
54     55  ...  [08/26/2020, 08:42:43, AM]
55     56  ...  [06/30/2020, 02:00:13, PM]
56     57  ...  [08/20/2020, 02:00:15, PM]
57     58  ...  [07/31/2020, 08:44:43, AM]
58     59  ...  [09/24/2020, 02:00:59, PM]
59     60  ...  [08/28/2020, 12:17:00, PM]

[60 rows x 13 columns]

In [311]:
merged_fb_dates = pd.merge(fb_new_index, fb_dates_df, how='outer', left_on='index', right_on='index', indicator=True)
merged_fb_dates

    index                           Post ID  ...  year _merge
0       1  163815626997995_2247842851928585  ...  2019   both
1       2  163815626997995_2178121278900743  ...  2019   both
2       3  163815626997995_2224957224217148  ...  2019   both
3       4  163815626997995_2127857120593826  ...  2019   both
4       5  163815626997995_2118764051503133  ...  2019   both
5       6   163815626997995_567473160423691  ...  2019   both
6       7   163815626997995_299896280911741  ...  2019   both
7       8  163815626997995_2220058584707012  ...  2019   both
8       9  163815626997995_2230106330368904  ...  2019   both
9      10   163815626997995_333057674003003  ...  2019   both
10     11   163815626997995_307786086550940  ...  2019   both
11     12  163815626997995_2086407854738753  ...  2019   both
12     13   163815626997995_445879205974812  ...  2019   both
13     14  163815626997995_2158951957484342  ...  2019   both
14     15  163815626997995_2188708107842060  ...  2019   both
15     16  163815626997995_1039672012891508  ...  2019   both
16     17  163815626997995_2074830022563203  ...  2019   both
17     18  163815626997995_2125544884158383  ...  2019   both
18     19   163815626997995_659993134518388  ...  2019   both
19     20  163815626997995_1237015259788586  ...  2019   both
20     21  163815626997995_2051144061598466  ...  2019   both
21     22  163815626997995_2134502726595932  ...  2019   both
22     23  163815626997995_2137176182995253  ...  2019   both
23     24  163815626997995_2121538151225723  ...  2019   both
24     25  163815626997995_2070446699668202  ...  2019   both
25     26  163815626997995_2360857287293807  ...  2019   both
26     27  163815626997995_2349306381782231  ...  2019   both
27     28  163815626997995_2473183669394501  ...  2019   both
28     29  163815626997995_2379531058759763  ...  2019   both
29     30  163815626997995_2414672348578967  ...  2019   both
30     31  163815626997995_2394687233910812  ...  2019   both
31     32  163815626997995_2306334576079412  ...  2019   both
32     33  163815626997995_2396871453692390  ...  2019   both
33     34  163815626997995_2544941092218758  ...  2019   both
34     35   163815626997995_442777316441180  ...  2019   both
35     36  163815626997995_2660835784031583  ...  2019   both
36     37   163815626997995_516966732370029  ...  2019   both
37     38  163815626997995_1691772297631304  ...  2019   both
38     39   163815626997995_545604132782615  ...  2020   both
39     40   163815626997995_233548857988277  ...  2020   both
40     41  163815626997995_1094969944203589  ...  2020   both
41     42   163815626997995_577273266243327  ...  2020   both
42     43   163815626997995_586122298677190  ...  2020   both
43     44   163815626997995_238121774051017  ...  2020   both
44     45   163815626997995_252822859161206  ...  2020   both
45     46  163815626997995_3100209363358592  ...  2020   both
46     47  163815626997995_3268804819832378  ...  2020   both
47     48   163815626997995_955219121616822  ...  2020   both
48     49   163815626997995_315939189682664  ...  2020   both
49     50   163815626997995_341645600563706  ...  2020   both
50     51   163815626997995_604032953849979  ...  2020   both
51     52   163815626997995_274170123791143  ...  2020   both
52     53  163815626997995_2700080293429895  ...  2020   both
53     54   163815626997995_225096068458728  ...  2020   both
54     55  163815626997995_3226448280734699  ...  2020   both
55     56  163815626997995_2351117388522924  ...  2020   both
56     57  163815626997995_3132922820119077  ...  2020   both
57     58  163815626997995_3151439228235605  ...  2020   both
58     59   163815626997995_328542921772260  ...  2020   both
59     60  163815626997995_3233012440078283  ...  2020   both

[60 rows x 17 columns]

## Website

In [357]:
website

                                            Page Title  ...  Bounce Rate
0                                            (not set)  ...     0.002778
1    Home Page | The Chicago Council on Science and...  ...     0.454988
2    A Window into Science 2021 | The Chicago Counc...  ...     0.785714
3    About | The Chicago Council on Science and Tec...  ...     0.456522
4    Mental Help: Impacts of Isolation, Racism, and...  ...     0.888889
..                                                 ...  ...          ...
218  Stuart Firestein presents C2ST Lecture on fail...  ...     1.000000
219  Conversations for Science | The Chicago Counci...  ...     1.000000
220  A Time for Change | The Chicago Council on Sci...  ...     1.000000
221  Head Banging: How Music and Concussions Impact...  ...     1.000000
222  Chemical Innovations - Molecular Modeling: A W...  ...     1.000000

[223 rows x 4 columns]

# Data Normalization

## Programs

In [26]:
new_programs

      ProgramID month  ... Female Speakers People of Color (informal)
0     100507-PS    10  ...               0                          0
1     102907-PS    10  ...               0                          0
2     022208-SS    02  ...               0                          0
3     031208-SS    03  ...               0                          0
4     092408-SS    09  ...               0                          0
..          ...   ...  ...             ...                        ...
273   090120-SS    09  ...               2                          0
274   092420-LS    09  ...               0                          0
275   101220-HW    10  ...               0                          0
276  050508-CEE    05  ...               0                          0
277  050708-CEE    05  ...               0                          0

[278 rows x 15 columns]

In [28]:
partners_ls = new_programs['Partner/ event'].values
len(partners_ls)

278

In [46]:
partner_dict = {}
i = 0
for partner in partners_ls: 
    if partner != 'none':
        if ';' in partner:
            partner = partner.strip().split(';')
            partner_dict[i] = partner
            i += 1
        elif ',' in partner:
            partner = partner.strip().split(',')
            partner_dict[i] = partner
        else:
            partner = partner.strip()
            partner_dict[i] = partner
            i += 1
    else:
        partner_dict[i] = partner
        i += 1

#partner_dict

In [51]:
new_partners_nolist = {}
additional_indexing = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

for k,v in partner_dict.items():
    if type(v) == list:
        i = 0
        for item in v:
            part = item.strip().lower()
            new_partners_nolist[str(k) + '-' + additional_indexing[i]] = part
            i += 1
    else:
        i = 0
        new_partners_nolist[str(k) + '-' + additional_indexing[i]] = v

len(new_partners_nolist)

321

In [64]:
indexed_partners = pd.DataFrame.from_dict(new_partners_nolist, orient='index')
#indexed_partners.reset_index(inplace=True)

     index                              0
0      0-A                              0
1      1-A                              0
2      2-A                              0
3      3-A                              0
4      4-A                              0
..     ...                            ...
316  259-A                            igb
317  259-B              kleinmuntz center
318  260-A  University of Illinois System
319  261-A                           none
320  262-A                           none

[321 rows x 2 columns]

In [69]:
#indexed_partners.rename(columns={'index': 'new_index', 0: 'partner name'}, inplace=True)
indexed_partners

    new_index                   partner name
0         0-A                              0
1         1-A                              0
2         2-A                              0
3         3-A                              0
4         4-A                              0
..        ...                            ...
316     259-A                            igb
317     259-B              kleinmuntz center
318     260-A  University of Illinois System
319     261-A                           none
320     262-A                           none

[321 rows x 2 columns]

In [81]:
test_df = new_programs.copy()
#test_df.reset_index(inplace=True)
#test_df.rename(columns={'index': 'new_index'}, inplace=True)

In [82]:
#test_df.drop('new_index', axis=1, inplace=True)
test_df['new_index'] = test_df.new_index.apply(lambda x: str(x) + '-' + additional_indexing[0])
test_df

    new_index   ProgramID  ... Female Speakers People of Color (informal)
0         0-A   100507-PS  ...               0                          0
1         1-A   102907-PS  ...               0                          0
2         2-A   022208-SS  ...               0                          0
3         3-A   031208-SS  ...               0                          0
4         4-A   092408-SS  ...               0                          0
..        ...         ...  ...             ...                        ...
273     273-A   090120-SS  ...               2                          0
274     274-A   092420-LS  ...               0                          0
275     275-A   101220-HW  ...               0                          0
276     276-A  050508-CEE  ...               0                          0
277     277-A  050708-CEE  ...               0                          0

[278 rows x 16 columns]

In [84]:
test_merged_partners = pd.merge(test_df, indexed_partners, how='outer', on='new_index', indicator=True)
test_merged_partners
#test_merged_partners.to_excel('/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/test_normalize_partners.xlsx')

    new_index  ProgramID  ...                          partner name      _merge
0         0-A  100507-PS  ...                                     0        both
1         1-A  102907-PS  ...                                     0        both
2         2-A  022208-SS  ...                                     0        both
3         3-A  031208-SS  ...                                     0        both
4         4-A  092408-SS  ...                                     0        both
..        ...        ...  ...                                   ...         ...
331     236-C        NaN  ...                           dark matter  right_only
332     238-B        NaN  ...  disability and human development uic  right_only
333     253-B        NaN  ...         chicago engineers' foundation  right_only
334     256-B        NaN  ...                      kleinmutz center  right_only
335     259-B        NaN  ...                     kleinmuntz center  right_only

[336 rows x 18 columns]

In [91]:
test_merged_partners.iloc[260]

new_index                                                       260-A
ProgramID                                                   050720-SS
month                                                              05
day                                                                07
year                                                               20
Program Title                 SFTF:Racial Disparity in COVID-19 Panel
Program Series                                                     SS
Type of Program                                              Original
Venue                                                   Facebook Live
Partner/ event                                                      0
Hours                                                               1
Attendance (in seats)                                               0
Live Stream                                                       199
Male Speakers                                                       1
Female Speakers                                                     3
People of Color (informal)                                          4
partner name                            University of Illinois System
_merge                                                           both
Name: 260, dtype: object

In [85]:
program_types = new_programs['Type of Program'].copy()
new_prog_types = []
for prog_type in program_types:
    new_type = prog_type.strip().lower()
    new_prog_types.append(new_type)
#new_prog_types

In [92]:
progs_types = []
for program in new_prog_types: 
    if program == 'original':
        progs_types.append(program.replace('original', '1'))
    elif program == 'signature':
        progs_types.append(program.replace('signature', '2'))
    elif program == 'speakeasy':
        progs_types.append(program.replace('speakeasy', '3'))
    elif program == 'booth':
        progs_types.append(program.replace('booth', '4'))
    elif program == 'local':
        progs_types.append(program.replace('local', '5'))
new_programs['Program Type Keys'] = pd.Series(progs_types)
new_programs

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

      ProgramID month  ... People of Color (informal) Program Type Keys
0     100507-PS    10  ...                          0                 1
1     102907-PS    10  ...                          0                 1
2     022208-SS    02  ...                          0                 1
3     031208-SS    03  ...                          0                 1
4     092408-SS    09  ...                          0                 1
..          ...   ...  ...                        ...               ...
273   090120-SS    09  ...                          0                 1
274   092420-LS    09  ...                          0                 1
275   101220-HW    10  ...                          0                 1
276  050508-CEE    05  ...                          0                 1
277  050708-CEE    05  ...                          0                 1

[278 rows x 16 columns]

In [87]:
new_program_unique = pd.Series(new_prog_types).unique()
new_program_unique

array(['original', 'signature', 'speakeasy', 'booth', 'local'],
      dtype=object)

In [93]:
programs_tbl = new_programs[['ProgramID', 'month', 'day', 'year', 'Program Title', 'Program Series', 'Program Type Keys', 'Venue', 'Hours', 'Attendance (in seats)', 'Live Stream', 'Male Speakers', 'Female Speakers', 'People of Color (informal)']].copy()
programs_tbl

      ProgramID month  ... Female Speakers People of Color (informal)
0     100507-PS    10  ...               0                          0
1     102907-PS    10  ...               0                          0
2     022208-SS    02  ...               0                          0
3     031208-SS    03  ...               0                          0
4     092408-SS    09  ...               0                          0
..          ...   ...  ...             ...                        ...
273   090120-SS    09  ...               2                          0
274   092420-LS    09  ...               0                          0
275   101220-HW    10  ...               0                          0
276  050508-CEE    05  ...               0                          0
277  050708-CEE    05  ...               0                          0

[278 rows x 14 columns]

## Youtube

In [202]:
#yt_better_dates.rename(columns={'video_title': 'Program Title'}, inplace=True)
video_titles = pd.DataFrame(yt_better_dates['Program Title'].apply(lambda x: x.lower().strip(':,-')))
video_titles

                                         Program Title
0    biomechanics of running: the science of moveme...
1    women in science symposium 2012 closing keynot...
2                             the science of addiction
3    the heart of marine biodiversity  saving the v...
4            fermilab and the new frontiers of physics
..                                                 ...
268  chicago council on science and technology wint...
269  chicago's water: protecting our precious resou...
270  chicago council on science and technology spri...
271  c2st: science in the new millenium 2008 - alan...
272  the threat of superbugs - robert a. weinstein,...

[273 rows x 1 columns]

In [214]:
programs_yt
program_titles = pd.DataFrame([programs_yt['Program Title'].apply(lambda x: x.lower().strip(':,-')), programs_yt['ProgramID']]).T
program_titles

                                         Program Title   ProgramID
0                               anniversary of sputnik   100507-PS
1                          nasa administrative griffin   102907-PS
2                                            stem cell   022208-SS
3                            future of science: rosner   031208-SS
4                                         alan leshner   092408-SS
..                                                 ...         ...
273                               uic involvement fair   090120-SS
274  the power of genomics: optimzing health outcom...   092420-LS
275           deploying shield: to illinois and beyond   101220-HW
276                          energy colloquium (day 1)  050508-CEE
277                          energy colloquium (day 2)  050708-CEE

[278 rows x 2 columns]

In [215]:
matching_titles = pd.merge(video_titles, program_titles, how='inner', indicator=True)
matching_titles

                                        Program Title   ProgramID _merge
0                            the science of addiction   032316-HW   both
1           fermilab and the new frontiers of physics   090617-PS   both
2   the heart of marine biodiversity: saving the v...  092816-CEE   both
3             making things meaningful in the ice age   041117-SS   both
4               failure: why science is so successful   102115-SS   both
5         extreme science: the u.s. antarctic program  042017-CEE   both
6   the study of ancient dna: knowledge from unexp...   082020-LS   both
7   forensic genomic technologies: new frontiers b...  062520-TEI   both
8                 the usefulness of useless knowledge   040617-SS   both
9   antibiotic hunters: discovering drugs in the o...   071117-LS   both
10  curators: behind the scenes of natural history...   082517-SS   both
11  challenges and opportunities in an emerging so...  040418-CEE   both
12  dietary supplements: stories of regulation, sa...   062017-HW   both
13  mindfully coping: strategies for children and ...   080520-HW   both
14             art, science, and the elegant universe   061720-PS   both
15             art, science, and the elegant universe   061720-PS   both
16                  new developments in mental health   092617-HW   both
17                  new developments in mental health   092617-HW   both
18  3d printing in action: an introduction to digi...  072120-TEI   both
19            lessons in biology taught by a pathogen   082720-LS   both
20               filtering the facts of kidney health   100519-HW   both
21    the future of trees: hope in a changing climate  041218-CEE   both
22                                     extreme storms  061418-CEE   both
23                            technology and politics  101017-TEI   both
24                      what is the brain initiative?   100115-LS   both
25  science is a verb. we must get sciencing. the ...   040418-SS   both
26                                    array of things  020619-TEI   both
27             climate disruption: what we can do now  030916-CEE   both
28  climate change and energy needs: finding a pat...  111716-CEE   both
29                  mindfulness, meditation, and yoga   022019-HW   both
30                                   unconscious bias   111317-SS   both
31                                   unconscious bias   111317-SS   both
32  recent advances in co2 storage science and tec...  032217-CEE   both
33     how sexual harassment culture infects academia   032119-SS   both
34                                           the moon   012511-PS   both
35  investing in science and education: an act of ...   022018-SS   both
36                                              tesla   080511-SS   both

In [222]:
yt_better_dates['program_title'] = yt_better_dates['Program Title'].apply(lambda x: x.lower())
yt_better_dates

     index  ...                                      program_title
0        0  ...  biomechanics of running: the science of moveme...
1        1  ...  women in science symposium 2012 closing keynot...
2        2  ...                           the science of addiction
3        3  ...  the heart of marine biodiversity  saving the v...
4        4  ...          fermilab and the new frontiers of physics
..     ...  ...                                                ...
268    268  ...  chicago council on science and technology wint...
269    269  ...  chicago's water: protecting our precious resou...
270    270  ...  chicago council on science and technology spri...
271    271  ...  c2st: science in the new millenium 2008 - alan...
272    272  ...  the threat of superbugs - robert a. weinstein,...

[273 rows x 14 columns]

In [229]:
test_yt_merge_on_prog_name = pd.merge(yt_better_dates, matching_titles, how='outer', left_on=yt_better_dates['program_title'], right_on=matching_titles['Program Title'])
test_yt_merge_on_prog_name.head()

                                               key_0  index  ...  ProgramID _merge_y
0  biomechanics of running: the science of moveme...      0  ...        NaN      NaN
1  women in science symposium 2012 closing keynot...      1  ...        NaN      NaN
2                           the science of addiction      2  ...  032316-HW     both
3  the heart of marine biodiversity  saving the v...      3  ...        NaN      NaN
4          fermilab and the new frontiers of physics      4  ...  090617-PS     both

[5 rows x 18 columns]

In [231]:
yt_tbl = test_yt_merge_on_prog_name[['ProgramID', 'Video', 'Program Title_x', 'month', 'day', 'year', 'Views', 'Watch time (hours)', 'Subscribers', 'Impressions', 'Impressions click-through rate (%)', '_merge_y']]
yt_tbl

     ProgramID        Video  ... Impressions click-through rate (%) _merge_y
0          NaN  7ZStUcT47Wo  ...                               4.49      NaN
1          NaN  FjJCJY8TfIU  ...                               7.95      NaN
2    032316-HW  bl2iGoOzB4o  ...                               4.66     both
3          NaN  K6fK_LIcDGE  ...                               8.35      NaN
4    090617-PS  xt2wDYDLsx8  ...                               3.90     both
..         ...          ...  ...                                ...      ...
274        NaN  BBDwDfETqk4  ...                               0.28      NaN
275        NaN  H3ZVLksBgg0  ...                               1.80      NaN
276        NaN  IYiw4PyLqTg  ...                               0.21      NaN
277        NaN  Ozc_WGCcIGY  ...                               1.20      NaN
278        NaN  PnQhLb6EvKw  ...                               0.32      NaN

[279 rows x 12 columns]

In [238]:
yt_tbl['ProgramID'] = yt_tbl.ProgramID.fillna(yt_tbl['month']+yt_tbl['day']+yt_tbl['year']+'-U')
youtube_tbl = yt_tbl.drop('_merge_y', axis=1)
youtube_tbl

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

       ProgramID        Video  ... Impressions Impressions click-through rate (%)
0    09132014- U  7ZStUcT47Wo  ...       87317                               4.49
1    08132012- U  FjJCJY8TfIU  ...       35696                               7.95
2      032316-HW  bl2iGoOzB4o  ...        6612                               4.66
3    10122016- U  K6fK_LIcDGE  ...       23115                               8.35
4      090617-PS  xt2wDYDLsx8  ...       41121                               3.90
..           ...          ...  ...         ...                                ...
274  11072013- U  BBDwDfETqk4  ...         358                               0.28
275  02242015- U  H3ZVLksBgg0  ...         111                               1.80
276  12102011- U  IYiw4PyLqTg  ...         467                               0.21
277  08132015- U  Ozc_WGCcIGY  ...         166                               1.20
278  11072013- U  PnQhLb6EvKw  ...         315                               0.32

[279 rows x 11 columns]

## Facebook

In [268]:
post_message_match_test = fb[['Post ID', 'Post Message']].copy()
post_message_match_test['post_normal'] = post_message_match_test['Post Message'].apply(lambda x: x.lower().replace('&amp;', 'and'))
post_message_match_test.head()

                            Post ID  ...                                    post_normal
1  163815626997995_2247842851928585  ...  the chicago council on science and technology
2  163815626997995_2178121278900743  ...  the chicago council on science and technology
3  163815626997995_2224957224217148  ...  the chicago council on science and technology
4  163815626997995_2127857120593826  ...                                        [empty]
5  163815626997995_2118764051503133  ...                                        [empty]

[5 rows x 3 columns]

In [258]:
program_titles.head()

                 Program Title  ProgramID
0       anniversary of sputnik  100507-PS
1  nasa administrative griffin  102907-PS
2                    stem cell  022208-SS
3    future of science: rosner  031208-SS
4                 alan leshner  092408-SS

In [278]:
program_names_for_match = list(program_titles['Program Title'].values)
#program_names_for_match

In [280]:
programs_fb_keys = {}
for fb_post in post_message_match_test.post_normal.values:
    for program_name in program_names_for_match:
        if program_name in fb_post:
            programs_fb_keys[program_name] = fb_post
len(programs_fb_keys)

6

In [289]:
matching_programs_fb_posts = pd.DataFrame.from_dict(programs_fb_keys, orient='index')
matching_programs_fb_posts.reset_index(inplace=True)
matching_programs_fb_posts.rename(columns={'index': 'program_title', 0:'fb_post_content'}, inplace=True)
matching_programs_fb_posts

                program_title                                    fb_post_content
0             array of things  chicago is growing smarter every day. want to ...
1                         eol  diversity in academia is in the public spotlig...
2          the earliest child  join us for a talk with professor zeray alemse...
3               leon lederman  this event will highlight dr. lederman’s contr...
4                        cern  join c2st on facebook live for a discussion on...
5  neutrino 2020 physics slam  join c2st and fermilab for the neutrino 2020 p...

In [313]:
programIDs_wfb_content = pd.merge(program_titles.copy(), matching_programs_fb_posts, how='outer', left_on='Program Title', right_on='program_title', indicator=True)
programIDs_wfb_content[programIDs_wfb_content['_merge'] == 'both']

                  Program Title  ... _merge
6                           eol  ...   both
32                leon lederman  ...   both
59                         cern  ...   both
219             array of things  ...   both
243          the earliest child  ...   both
267  neutrino 2020 physics slam  ...   both

[6 rows x 5 columns]

In [335]:
fbIDs_program_names = pd.merge(post_message_match_test, matching_programs_fb_posts, how='outer', left_on='post_normal', right_on='fb_post_content', indicator=True)
fbIDs_program_names.drop('_merge', axis=1, inplace=True)

In [317]:
#merged_fb_dates.drop('_merge', axis=1, inplace=True)
merged_fb_dates['post_normal'] = merged_fb_dates['Post Message'].apply(lambda x: x.lower().replace('&amp;', 'and'))
merged_fb_dates

    index  ...                                        post_normal
0       1  ...      the chicago council on science and technology
1       2  ...      the chicago council on science and technology
2       3  ...      the chicago council on science and technology
3       4  ...                                            [empty]
4       5  ...                                            [empty]
5       6  ...  resilience, empathy, and plasticity are import...
6       7  ...  chicago is growing smarter every day. want to ...
7       8  ...                                            [empty]
8       9  ...                                            [empty]
9      10  ...  diversity in academia is in the public spotlig...
10     11  ...  star wars – the fight of the light side of the...
11     12  ...                                            [empty]
12     13  ...  a recent breakthrough in our war against cance...
13     14  ...                                            [empty]
14     15  ...                                            [empty]
15     16  ...  star wars – the fight of the light side of the...
16     17  ...                                            [empty]
17     18  ...                                            [empty]
18     19  ...  the recycling industry is in crisis. after dec...
19     20  ...  star wars – the fight of the light side of the...
20     21  ...  the chicago council on science and technology ...
21     22  ...                                            [empty]
22     23  ...                                            [empty]
23     24  ...                                            [empty]
24     25  ...  horizon pharma visited  perspectives charter s...
25     26  ...                                            [empty]
26     27  ...                                            [empty]
27     28  ...                                            [empty]
28     29  ...                                            [empty]
29     30  ...                                            [empty]
30     31  ...                                            [empty]
31     32  ...  the chicago council on science and technology ...
32     33  ...      the chicago council on science and technology
33     34  ...  as a part of our ongoing initiative to introdu...
34     35  ...  join us as c2st hosts renowned mathematician e...
35     36  ...  join us for a talk with professor zeray alemse...
36     37  ...  this event will highlight dr. lederman’s contr...
37     38  ...  inclusive practices and promoting diversity ha...
38     39  ...  join c2st and dr. sarah connolly to examine he...
39     40  ...  the shortage of personal protective equipment ...
40     41  ...  coronavirus disease 2019 (covid-19) has brough...
41     42  ...  join c2st and our panel of local experts for a...
42     43  ...  join c2st for our 5th science from the frontli...
43     44  ...  dr. karla satchell has been a frequent name in...
44     45  ...  join c2st and koval for a virtual tour and tas...
45     46  ...                                            [empty]
46     47  ...                                            [empty]
47     48  ...  ever wondered how 3d printers actually work? j...
48     49  ...  dr. kehl-fie will discuss how a pathogen and h...
49     50  ...  join c2st and orson morrison, psyd for a candi...
50     51  ...  join c2st and dean bashir to explore the grand...
51     52  ...  join c2st as dr. hughes discusses recent and r...
52     53  ...  join c2st on facebook live for a discussion on...
53     54  ...  join c2st and fermilab for the neutrino 2020 p...
54     55  ...                                            [empty]
55     56  ...  join author michael zapata, and physicist, dr....
56     57  ...  learn how ancient dna is currently being used ...
57     58  ...                                            [empty]
58     59  ...  the power of genomics: optimizing health outco...
59     60  ...  have you checked out our &quot;science from th...

[60 rows x 17 columns]

In [337]:
fb_tbl = pd.merge(merged_fb_dates.copy(), fbIDs_program_names, how='outer', on='Post ID')
fb_tbl

    index  ...                                    fb_post_content
0       1  ...                                                NaN
1       2  ...                                                NaN
2       3  ...                                                NaN
3       4  ...                                                NaN
4       5  ...                                                NaN
5       6  ...                                                NaN
6       7  ...  chicago is growing smarter every day. want to ...
7       8  ...                                                NaN
8       9  ...                                                NaN
9      10  ...  diversity in academia is in the public spotlig...
10     11  ...                                                NaN
11     12  ...                                                NaN
12     13  ...                                                NaN
13     14  ...                                                NaN
14     15  ...                                                NaN
15     16  ...                                                NaN
16     17  ...                                                NaN
17     18  ...                                                NaN
18     19  ...                                                NaN
19     20  ...                                                NaN
20     21  ...                                                NaN
21     22  ...                                                NaN
22     23  ...                                                NaN
23     24  ...                                                NaN
24     25  ...                                                NaN
25     26  ...                                                NaN
26     27  ...                                                NaN
27     28  ...                                                NaN
28     29  ...                                                NaN
29     30  ...                                                NaN
30     31  ...                                                NaN
31     32  ...                                                NaN
32     33  ...                                                NaN
33     34  ...                                                NaN
34     35  ...                                                NaN
35     36  ...  join us for a talk with professor zeray alemse...
36     37  ...  this event will highlight dr. lederman’s contr...
37     38  ...                                                NaN
38     39  ...                                                NaN
39     40  ...                                                NaN
40     41  ...                                                NaN
41     42  ...                                                NaN
42     43  ...                                                NaN
43     44  ...                                                NaN
44     45  ...                                                NaN
45     46  ...                                                NaN
46     47  ...                                                NaN
47     48  ...                                                NaN
48     49  ...                                                NaN
49     50  ...                                                NaN
50     51  ...                                                NaN
51     52  ...                                                NaN
52     53  ...  join c2st on facebook live for a discussion on...
53     54  ...  join c2st and fermilab for the neutrino 2020 p...
54     55  ...                                                NaN
55     56  ...                                                NaN
56     57  ...                                                NaN
57     58  ...                                                NaN
58     59  ...                                                NaN
59     60  ...                                                NaN

[60 rows x 21 columns]

In [343]:
fb_tbl.columns
program_titles.head()

                 Program Title  ProgramID
0       anniversary of sputnik  100507-PS
1  nasa administrative griffin  102907-PS
2                    stem cell  022208-SS
3    future of science: rosner  031208-SS
4                 alan leshner  092408-SS

In [347]:
facebook_tbl = fb_tbl[['Post ID', 'Permalink', 'program_title', 'month', 'day', 'year', 'post_normal_x', 'Type', 'Lifetime Post Total Impressions', 'Lifetime Total Video Views','Lifetime Unique Video Views']]
facebook_tbl.program_title.fillna('U', inplace=True)
facebook_tbl = pd.merge(facebook_tbl, program_titles, how='outer', left_on='program_title', right_on='Program Title')
facebook_tbl.drop('Program Title', axis=1, inplace=True)
facebook_tbl

/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:4536: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

                              Post ID  ...   ProgramID
0    163815626997995_2247842851928585  ...         NaN
1    163815626997995_2178121278900743  ...         NaN
2    163815626997995_2224957224217148  ...         NaN
3    163815626997995_2127857120593826  ...         NaN
4    163815626997995_2118764051503133  ...         NaN
..                                ...  ...         ...
327                               NaN  ...   090120-SS
328                               NaN  ...   092420-LS
329                               NaN  ...   101220-HW
330                               NaN  ...  050508-CEE
331                               NaN  ...  050708-CEE

[332 rows x 12 columns]

In [355]:
#facebook_tbl.drop(range(60,332), inplace=True)
facebook_tbl.ProgramID.fillna(facebook_tbl['month'] + facebook_tbl['day'] + facebook_tbl['year']+'-U', inplace=True)
facebook_tbl

                             Post ID  ...   ProgramID
0   163815626997995_2247842851928585  ...  05312019-U
1   163815626997995_2178121278900743  ...  04172019-U
2   163815626997995_2224957224217148  ...  05172019-U
3   163815626997995_2127857120593826  ...  03132019-U
4   163815626997995_2118764051503133  ...  03062019-U
5    163815626997995_567473160423691  ...  02282019-U
6   163815626997995_2220058584707012  ...  05142019-U
7   163815626997995_2230106330368904  ...  05202019-U
8    163815626997995_307786086550940  ...  04032019-U
9   163815626997995_2086407854738753  ...  02122019-U
10   163815626997995_445879205974812  ...  05302019-U
11  163815626997995_2158951957484342  ...  04042019-U
12  163815626997995_2188708107842060  ...  04242019-U
13  163815626997995_1039672012891508  ...  04032019-U
14  163815626997995_2074830022563203  ...  02042019-U
15  163815626997995_2125544884158383  ...  03112019-U
16   163815626997995_659993134518388  ...  06112019-U
17  163815626997995_1237015259788586  ...  04032019-U
18  163815626997995_2051144061598466  ...  01182019-U
19  163815626997995_2134502726595932  ...  03182019-U
20  163815626997995_2137176182995253  ...  03202019-U
21  163815626997995_2121538151225723  ...  03082019-U
22  163815626997995_2070446699668202  ...  02012019-U
23  163815626997995_2360857287293807  ...  08052019-U
24  163815626997995_2349306381782231  ...  07292019-U
25  163815626997995_2473183669394501  ...  10072019-U
26  163815626997995_2379531058759763  ...  08162019-U
27  163815626997995_2414672348578967  ...  09052019-U
28  163815626997995_2394687233910812  ...  08252019-U
29  163815626997995_2306334576079412  ...  07042019-U
30  163815626997995_2396871453692390  ...  08262019-U
31  163815626997995_2544941092218758  ...  11112019-U
32   163815626997995_442777316441180  ...  11212019-U
33  163815626997995_1691772297631304  ...  12062019-U
34   163815626997995_545604132782615  ...  06022020-U
35   163815626997995_233548857988277  ...  04162020-U
36  163815626997995_1094969944203589  ...  04072020-U
37   163815626997995_577273266243327  ...  05072020-U
38   163815626997995_586122298677190  ...  05202020-U
39   163815626997995_238121774051017  ...  04092020-U
40   163815626997995_252822859161206  ...  05262020-U
41  163815626997995_3100209363358592  ...  07132020-U
42  163815626997995_3268804819832378  ...  09092020-U
43   163815626997995_955219121616822  ...  07212020-U
44   163815626997995_315939189682664  ...  08272020-U
45   163815626997995_341645600563706  ...  08052020-U
46   163815626997995_604032953849979  ...  07092020-U
47   163815626997995_274170123791143  ...  06252020-U
48  163815626997995_3226448280734699  ...  08262020-U
49  163815626997995_2351117388522924  ...  06302020-U
50  163815626997995_3132922820119077  ...  08202020-U
51  163815626997995_3151439228235605  ...  07312020-U
52   163815626997995_328542921772260  ...  09242020-U
53  163815626997995_3233012440078283  ...  08282020-U
54   163815626997995_299896280911741  ...  020619-TEI
55   163815626997995_333057674003003  ...   101408-LS
56  163815626997995_2660835784031583  ...   101619-LS
57   163815626997995_516966732370029  ...   060510-SS
58  163815626997995_2700080293429895  ...   050112-PS
59   163815626997995_225096068458728  ...   070220-PS

[60 rows x 12 columns]

# Data Export

## Programs

In [ ]:
#partners_tbl.to_csv(path_or_buf='/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/db_input_data/partners_tbl.csv')

In [ ]:
#program_series_tbl.to_csv(path_or_buf='/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/db_input_data/program_series_tbl.csv')

In [ ]:
#new_venues_tbl.to_csv(path_or_buf='/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/db_input_data/venues_tbl.csv')

In [96]:
#program_type_tbl.to_csv(path_or_buf='/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/db_input_data/program_type_tbl.csv')

In [97]:
#programs_tbl.to_csv(path_or_buf='/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/db_input_data/program_tbl.csv')

## Youtube

In [165]:
#yt_better_dates.to_csv(path_or_buf='/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/youtube_better_dates.csv')

In [239]:
#youtube_tbl.to_csv(path_or_buf='/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/db_input_data/youtube_tbl.csv')

## Facebook

In [356]:
#facebook_tbl.to_csv(path_or_buf='/content/drive/MyDrive/UMSI W21/SI564/Assignments/final_project/db_input_data/facebook_tbl.csv')